### ISSUE TITLE
On calling CreateQueue: 500 Can't connect to sqs.us-east-1.amazonaws.com:443 (certificate verify failed) at /usr/lib/perl5/site_perl/5.8.8/Replay/EventSystem/AWSQueue.pm line 169.

### ISSUE THREAD

**Issue by byterock** [gisle/mozilla-ca#7]
I think my buddy Dave already put a patch to fix the above.

you can see my local fix on this blog post  which was to roll back my Mozill::CA to a working version

http://blogs.perl.org/users/byterock/2015/03/ca-ssl-https-heck.html

**Comment by abh** [comment]
Doing "ALL:ALL" isn't a fix; you might just as well stop verifying the certs then.
